### ISSUE TITLE
[Bug]: Extension not loading

### ISSUE THREAD

**Issue by Kamin-13** [continue-revolution/sd-forge-animatediff#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

The extension not loading after installation and downloading models

Does not appear on txt2img or img2img

### Steps to reproduce the problem

1. Install this extension
2. Download models into the folder
3. Apply and restart

### What should have happened?

Extension appear on txt2img and img2img

### Commit where the problem happens

webui: https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/86ee2d9462cc3baf8618430513e2fc0b6e4cabff
extension: 2.0.2-f (#430)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--listen --enable-insecure-extension-access
```

### Console logs

```Shell
-
```

### Additional information

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_latent.py", line 10, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_output.py", line 15, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_settings.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_settings.py", line 4, in <module>
        from scripts.animatediff_ui import supported_save_formats
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "/home/kamin/Desktop/stable-diffusion-webui-forge/extensions/sd-forge-animatediff/scripts/animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---

**Comment by leomaxwell973** [comment]
unet_patcher : https://github.com/continue-revolution/sd-forge-animatediff/issues/26#issuecomment-2837390949

ldm_patched : https://github.com/continue-revolution/sd-forge-animatediff/issues/25#issuecomment-2837397993
