### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'ldm_patched'

### ISSUE THREAD

**Issue by AndyH3H1** [continue-revolution/sd-forge-animatediff#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I fresh installed AMDGPUs version https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge?tab=readme-ov-file
After first startup I tried to install sd-forge-animatediff over Extensions tab or via git pull (I tried both independently).

The extension isn´t loading

Bug #15 seems to be a bit similar, but other dependencies are missing, so maybe it´s another problem

### Steps to reproduce the problem

1. Go to extensions -> install from URL -> https://github.com/continue-revolution/sd-forge-animatediff

I also tried a fresh install and used git clone https://github.com/continue-revolution/sd-forge-animatediff in extensions folder

2. After reloading or restarting webui-user.bat the error happens.

### What should have happened?

It should start without a problem

### Commit where the problem happens

webui: stable-diffusion-webui-amdgpu-forge f2.0.1v1.10.1-1.10.1
extension: sd-forge-animatediff - latest version

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--zluda --theme dark
```

### Console logs

```Shell
ONNX: version=1.18.1 provider=CUDAExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
==============================================================================
You are running torch 2.3.0+cu118.
The program is tested to work with torch 2.3.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
ControlNet preprocessor location: D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\models\ControlNetPreprocessor
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff.py", line 10, in <module>
        from scripts.animatediff_infv2v import AnimateDiffInfV2V
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 5, in <module>
        from ldm_patched.modules.model_management import get_torch_device, soft_empty_cache
    ModuleNotFoundError: No module named 'ldm_patched'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_latent.py", line 10, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_output.py", line 15, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_settings.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_settings.py", line 4, in <module>
        from scripts.animatediff_ui import supported_save_formats
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "D:\AI\StableDiffusion\stable-diffusion-webui-amdgpu-forge\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

---
```

**Comment by dawgakka** [comment]
same problem

**Comment by Codrenaa** [comment]
same problem :(

**Comment by dawgakka** [comment]
> same problem :(

The problem went away when I downloaded forges "Previous" Version
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/849
AnimateDiff and the AnimateDiff FOR forge doesn't tend to work with new versions

**Comment by Codrenaa** [comment]
Downloading the old version and not running update.bat worked. Thank you!

**Comment by leomaxwell973** [comment]
https://github.com/continue-revolution/sd-forge-animatediff/issues/25#issuecomment-2837397993

**Comment by crawlingsnail9** [comment]
> Downloading the old version and not running update.bat worked. Thank you!
Could you please offer some advice? This solution didn't work for me.
I downloaded the file from this link: https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/previous/webui_forge_cu121_torch21_f0017.7z. When I run run.bat directly without executing update.bat first, the following error occurs.
<img width="2085" height="1197" alt="Image" src="https://github.com/user-attachments/assets/89c65925-531f-431c-9d73-129d2b9b9136" />
