### ISSUE TITLE
[Bug]: Error when using AnimateDiff Forge since today

### ISSUE THREAD

**Issue by eliasprompt** [continue-revolution/sd-forge-animatediff#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Since Today I'm experimenting this issue and can't generate images. Yesterday it worked fine. I did a clean new installation but still the same problem

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

AnimateDiff should work propely like always

### Commit where the problem happens

webui: f0.0.15v1.8.0rc-latest-225-g2a7fb1be  python: 3.10.6  •  torch: 2.1.2+cu121
extension: c25a46d3]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Already up to date.
venv "D:\StableDiffusion_FORGE_UI\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.15v1.8.0rc-latest-225-g2a7fb1be
Commit hash: 2a7fb1be2412cc7bb83c755eed30408fc4155211
Launching Web UI with arguments: --ckpt-dir D:/Stable_Diffusion_ALL/Models/Stable-difussion
Total VRAM 12287 MB, total RAM 24521 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: D:\StableDiffusion_FORGE_UI\webui\models\ControlNetPreprocessor
Loading weights [15012c538f] from D:\StableDiffusion_FORGE_UI\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
model_type EPS
UNet ADM Dimension 0
2024-02-24 00:14:14,739 - ControlNet - INFO - ControlNet UI callback registered.
Using pytorch attention in VAE
Running on local URL:  http://127.0.0.1:7860
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

To create a public link, set `share=True` in `launch()`.
Startup time: 72.4s (initial startup: 0.4s, prepare environment: 16.4s, import torch: 17.2s, import gradio: 11.2s, setup paths: 9.1s, import ldm: 0.2s, initialize shared: 1.1s, other imports: 6.9s, setup gfpgan: 0.1s, list SD models: 2.4s, load scripts: 6.1s, create ui: 1.2s, gradio launch: 0.7s).
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Loading VAE weights specified in settings: D:\StableDiffusion_FORGE_UI\webui\models\VAE\vae-ft-mse-840000-ema-pruned.vae.pt
To load target model SD1ClipModel
Begin to load 1 model
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  11229.1259765625
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Estimated Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining Memory (MB) =  9750.918354034424
Moving model(s) has taken 0.98 seconds
Model loaded in 4.5s (load weights from disk: 0.3s, forge instantiate config: 0.1s, forge load real models: 2.2s, load VAE: 0.5s, calculate empty prompt: 1.3s).
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.15v1.8.0rc-latest-225-g2a7fb1be
Commit hash: 2a7fb1be2412cc7bb83c755eed30408fc4155211
Launching Web UI with arguments: --ckpt-dir D:/Stable_Diffusion_ALL/Models/Stable-difussion
Total VRAM 12287 MB, total RAM 24521 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: D:\StableDiffusion_FORGE_UI\webui\models\ControlNetPreprocessor
Loading weights [15012c538f] from D:\StableDiffusion_FORGE_UI\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
model_type EPS
UNet ADM Dimension 0
2024-02-24 00:16:20,299 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.5s (prepare environment: 3.5s, import torch: 4.8s, import gradio: 1.1s, setup paths: 1.0s, initialize shared: 0.2s, other imports: 0.6s, load scripts: 2.9s, create ui: 1.0s, gradio launch: 0.3s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Loading VAE weights specified in settings: D:\StableDiffusion_FORGE_UI\webui\models\VAE\vae-ft-mse-840000-ema-pruned.vae.pt
To load target model SD1ClipModel
Begin to load 1 model
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  11229.1259765625
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Estimated Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining Memory (MB) =  9750.918354034424
Moving model(s) has taken 0.11 seconds
Model loaded in 4.1s (load weights from disk: 0.3s, forge load real models: 2.2s, load VAE: 1.2s, calculate empty prompt: 0.3s).
Calculating sha256 for D:\Stable_Diffusion_ALL\Models\Stable-difussion\MistoonAnime\mistoonAnime_v20.safetensors: c35e1054c0a18d7d761541dd2a991d8567ef0af78f4d909cb118fb568f16822c
Loading weights [c35e1054c0] from D:\Stable_Diffusion_ALL\Models\Stable-difussion\MistoonAnime\mistoonAnime_v20.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['model_ema.decay', 'model_ema.num_updates'])
Loading VAE weights specified in settings: D:\StableDiffusion_FORGE_UI\webui\models\VAE\vae-ft-mse-840000-ema-pruned.vae.pt
To load target model SD1ClipModel
Begin to load 1 model
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  11194.14453125
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Estimated Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining Memory (MB) =  9715.936908721924
Moving model(s) has taken 0.21 seconds
Model loaded in 22.7s (unload existing model: 0.4s, calculate hash: 20.0s, forge load real models: 1.4s, load VAE: 0.5s, calculate empty prompt: 0.3s).
2024-02-24 00:17:40,966 - ControlNet - INFO - Preview Resolution = 578
Automatic Memory Management: 128 Modules in 0.02 seconds.
2024-02-24 00:17:45,364 - ControlNet - INFO - Preview Resolution = 578
Automatic Memory Management: 0 Modules in 0.00 seconds.
2024-02-24 00:17:59,844 - AnimateDiff - INFO - AnimateDiff process start.
2024-02-24 00:17:59,844 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\model\mm_sd_v15_v2.ckpt
2024-02-24 00:18:25,645 - AnimateDiff - INFO - Guessed mm_sd_v15_v2.ckpt architecture: MotionModuleType.AnimateDiffV2
2024-02-24 00:18:26,323 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2024-02-24 00:18:26,325 - AnimateDiff - INFO - AnimateDiff + ControlNet will generate 12 frames.
2024-02-24 00:18:26,496 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-02-24 00:18:26,498 - ControlNet - INFO - Using preprocessor: dw_openpose_full
2024-02-24 00:18:26,499 - ControlNet - INFO - preprocessor resolution = 578
Automatic Memory Management: 0 Modules in 0.00 seconds.
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
[] []
2024-02-24 00:18:43,370 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\Stable_Diffusion_ALL\Models\Controlnet\control_v11p_sd15_openpose.pth
                                  2024-02-24 00:19:03,427 - AnimateDiff - INFO - Setting DDIM alpha.
To load target model SD1ClipModel]
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free Memory (MB) =  10561.67431640625
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Estimated Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining Memory (MB) =  9537.67431640625
Moving model(s) has taken 6.54 seconds
2024-02-24 00:19:12,445 - ControlNet - INFO - ControlNet Method dw_openpose_full patched.
2024-02-24 00:19:12,456 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet.
To load target model BaseModel
To load target model MotionWrapper
To load target model ControlNet
Begin to load 3 models
Reuse 0 loaded models
Reuse 0 loaded models
Reuse 0 loaded models
[Memory Management] Current Free Memory (MB) =  11179.29736328125
[Memory Management] Model Memory (MB) =  1639.4137649536133
[Memory Management] Estimated Inference Memory (MB) =  12663.212788085937
[Memory Management] Estimated Remaining Memory (MB) =  -3123.3291897583003
[Memory Management] Requested Async Preserved Memory (MB) =  0.0
[Async Memory Management] Parameters Loaded to Async Stream (MB) =  1639.406135559082
[Async Memory Management] Parameters Loaded to GPU (MB) =  0.0
[Memory Management] Current Free Memory (MB) =  11179.29736328125
[Memory Management] Model Memory (MB) =  866.7327880859375
[Memory Management] Estimated Inference Memory (MB) =  12663.212788085937
[Memory Management] Estimated Remaining Memory (MB) =  -2350.6482128906246
[Memory Management] Requested Async Preserved Memory (MB) =  0.0
[Async Memory Management] Parameters Loaded to Async Stream (MB) =  864.4281005859375
[Async Memory Management] Parameters Loaded to GPU (MB) =  0.0
[Memory Management] Current Free Memory (MB) =  11179.29736328125
[Memory Management] Model Memory (MB) =  689.0852355957031
[Memory Management] Estimated Inference Memory (MB) =  12663.212788085937
[Memory Management] Estimated Remaining Memory (MB) =  -2173.00066040039
[Memory Management] Requested Async Preserved Memory (MB) =  0.0
[Async Memory Management] Parameters Loaded to Async Stream (MB) =  689.0852355957031
[Async Memory Management] Parameters Loaded to GPU (MB) =  0.0
Moving model(s) has taken 17.77 seconds
  0%|                                                                                           | 0/25 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "D:\StableDiffusion_FORGE_UI\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\StableDiffusion_FORGE_UI\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\modules\txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "D:\StableDiffusion_FORGE_UI\webui\modules\processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "D:\StableDiffusion_FORGE_UI\webui\modules\processing.py", line 923, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\StableDiffusion_FORGE_UI\webui\modules\processing.py", line 1273, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\StableDiffusion_FORGE_UI\webui\modules\sd_samplers_kdiffusion.py", line 251, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\StableDiffusion_FORGE_UI\webui\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "D:\StableDiffusion_FORGE_UI\webui\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "D:\StableDiffusion_FORGE_UI\webui\modules_forge\forge_sampler.py", line 83, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "D:\StableDiffusion_FORGE_UI\webui\ldm_patched\modules\samplers.py", line 289, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\StableDiffusion_FORGE_UI\webui\ldm_patched\modules\samplers.py", line 256, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\scripts\animatediff_infv2v.py", line 148, in mm_sd_forward
    out = apply_model(info["input"][_context], info["timestep"][_context], **info_c)
  File "D:\StableDiffusion_FORGE_UI\webui\ldm_patched\modules\model_base.py", line 89, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 867, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\StableDiffusion_FORGE_UI\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 64, in forward_timestep_embed
    x = modifier(x, 'after', layer, layer_index, ts, transformer_options)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 85, in mm_block_modifier
    return self.mm.down_blocks[mm_idx0].motion_modules[mm_idx1](x)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\motion_module.py", line 127, in forward
    return self.temporal_transformer(x)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\motion_module.py", line 185, in forward
    hidden_states = block(hidden_states)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\motion_module.py", line 239, in forward
    hidden_states = attention_block(norm_hidden_states) + hidden_states
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\motion_module.py", line 329, in forward
    x = self.pos_encoder(x)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StableDiffusion_FORGE_UI\webui\extensions\sd-forge-animatediff\motion_module.py", line 264, in forward
    x = x + self.pe[:, :x.size(1)].type(x.dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
*** Error completing request
*** Arguments: ('task(i8a1pp30bv947qu)', <gradio.routes.Request object at 0x000001AFA6AE1240>, '(masterpiece, best quality:1.3), (25 years old girl:1.5) WITH SUNGLASSES, sitting on a rock playing an ukelele, (a magical waterfall with flowing water behind her:1.1), (closed eyes:1.3), (the music notes burst out to fill the air:1.5), she is surrounded by (flying and swirling magical music notes:1.7), colorfull and vibrant-fluid dynamic movement of (floating music symbols:1.3) of (crotchet note and octave clef:1.5), the composition captures the essence of (motion and vitality:1.3), placing viewers in the heart of a high-energy moment in the style of studio gibly, nadegata style,  <lora:more_details:0.7>  <lora:nadev1:0.3> <lora:Light and Shadow:0.2> <lora:NebulaDream_v1:0.2> <lora:Unholy:0.2>', '((disfigured)), ((bad art)), ((deformed)),((extra limbs)), ((extra barrel)),((b&w)), weird colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), (((tripod))), (((tube))),ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs, extra legs, extra arms,  EXTRA HANDS, cross-eye, body out of frame, bad art, bad anatomy, (((umbrella))), ((BAD HANDS)), ((BAD FINGERS)), ((watermark, username, nickname, signature, text, letters, characters)), ((open eyes)), ((simple background))', [], 25, 'DPM++ 2M Karras', 1, 1, 7, 1024, 576, True, 0.15, 1.1, 'R-ESRGAN 4x+ Anime6B', 13, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, 3024528887, False, -1, 0, 0, 0, False, <scripts.animatediff_ui.AnimateDiffProcess object at 0x000001AFA6B3FA30>, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8), mask_image=None, hr_option='Both', enabled=True, module='dw_openpose_full', model='control_v11p_sd15_openpose [cab727d4]', weight=1, image={'image': array([[[  9,  42,  73],
***         [  2,  37,  74],
***         [  3,  39,  72],
***         ...,
***         [ 12,  72, 101],
***         [ 11,  78, 107],
***         [ 17,  73, 101]],
***
***        [[  2,  38,  72],
***         [  3,  40,  74],
***         [  4,  41,  71],
***         ...,
***         [ 12,  72, 101],
***         [ 11,  77, 106],
***         [ 13,  79, 109]],
***
***        [[  4,  39,  71],
***         [  5,  40,  72],
***         [  4,  41,  70],
***         ...,
***         [ 11,  72, 101],
***         [ 12,  78, 104],
***         [ 12,  78, 109]],
***
***        ...,
***
***        [[ 71,  28,  56],
***         [ 70,  28,  57],
***         [ 69,  28,  56],
***         ...,
***         [ 35,  63,  70],
***         [ 32,  68,  71],
***         [ 34,  75,  79]],
***
***        [[ 71,  29,  56],
***         [ 71,  28,  56],
***         [ 69,  29,  55],
***         ...,
***         [ 35,  63,  69],
***         [ 34,  68,  73],
***         [ 35,  71,  77]],
***
***        [[ 69,  32,  54],
***         [ 70,  26,  55],
***         [ 70,  26,  57],
***         ...,
***         [ 35,  62,  69],
***         [ 39,  70,  71],
***         [ 41,  67,  72]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Just Resize', processor_res=578, threshold_a=0.5, threshold_b=0.5, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='ControlNet is more important', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=array([[[  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0],
***         ...,
***         [  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0]],
***
***        [[  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0],
***         ...,
***         [  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0]],
***
***        [[  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0],
***         ...,
***         [  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0]],
***
***        ...,
***
***        [[  5,   5,   5],
***         [  4,   4,   4],
***         [  4,   4,   4],
***         ...,
***         [144, 144, 144],
***         [153, 153, 153],
***         [154, 154, 154]],
***
***        [[  6,   6,   6],
***         [  5,   5,   5],
***         [  5,   5,   5],
***         ...,
***         [131, 131, 131],
***         [141, 141, 141],
***         [143, 143, 143]],
***
***        [[  7,   7,   7],
***         [  6,   6,   6],
***         [  5,   5,   5],
***         ...,
***         [131, 131, 131],
***         [140, 140, 140],
***         [145, 145, 145]]], dtype=uint8), mask_image=None, hr_option='Both', enabled=False, module='softedge_pidinet', model='control_v11p_sd15_softedge [a8575a2a]', weight=0.75, image={'image': array([[[  9,  42,  73],
***         [  2,  37,  74],
***         [  3,  39,  72],
***         ...,
***         [ 12,  72, 101],
***         [ 11,  78, 107],
***         [ 17,  73, 101]],
***
***        [[  2,  38,  72],
***         [  3,  40,  74],
***         [  4,  41,  71],
***         ...,
***         [ 12,  72, 101],
***         [ 11,  77, 106],
***         [ 13,  79, 109]],
***
***        [[  4,  39,  71],
***         [  5,  40,  72],
***         [  4,  41,  70],
***         ...,
***         [ 11,  72, 101],
***         [ 12,  78, 104],
***         [ 12,  78, 109]],
***
***        ...,
***
***        [[ 71,  28,  56],
***         [ 70,  28,  57],
***         [ 69,  28,  56],
***         ...,
***         [ 35,  63,  70],
***         [ 32,  68,  71],
***         [ 34,  75,  79]],
***
***        [[ 71,  29,  56],
***         [ 71,  28,  56],
***         [ 69,  29,  55],
***         ...,
***         [ 35,  63,  69],
***         [ 34,  68,  73],
***         [ 35,  71,  77]],
***
***        [[ 69,  32,  54],
***         [ 70,  26,  55],
***         [ 70,  26,  57],
***         ...,
***         [ 35,  62,  69],
***         [ 39,  70,  71],
***         [ 41,  67,  72]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Just Resize', processor_res=512, threshold_a=0.5, threshold_b=0.5, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='ControlNet is more important', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\StableDiffusion_FORGE_UI\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable
```

**Comment by continue-revolution** [comment]
I guess there was some weird module moving issue. I'll try to push a fix today

**Comment by eliasprompt** [comment]
> I guess there was some weird module moving issue. I'll try to push a fix today

Thanks for the reply. I reinstalled everything (Phyton, GIT, Nvidia Drivers and A1111 webui's (FORGE and normal webui) and the problem is still there. The issue appears in forge and normal a1111. Will wait for the updated fixed version. Thanks you

**Comment by MaxMacro** [comment]
> I guess there was some weird module moving issue. I'll try to push a fix today

Any update on this fix? I just discovered how awesome Forge is after leaving A1111 and was really hoping to use Animatediff and noticed it wasn't working currently.

**Comment by continue-revolution** [comment]
fixed
